name: Bandi Parkops

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Start
        run: |
          docker-compose -f /home/ubuntu/bandithemepark-parkops/docker-compose.yml up -d --build
